# Generated by Django 5.1.2 on 2025-02-24 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='palestrante',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='palestrantes', to='conferencias.evento'),
            preserve_default=False,
        ),
    ]
