# Generated by Django 5.1.2 on 2025-02-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0002_palestrante_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='conferencias.evento'),
            preserve_default=False,
        ),
    ]
