# Generated by Django 5.1.2 on 2025-02-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferencias', '0004_alter_ingresso_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresso',
            name='tipo',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
